# Generated by Django 3.0.10 on 2020-10-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_dests', models.IntegerField()),
                ('name', models.TextField(max_length=35)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
