# Generated by Django 3.0.10 on 2020-10-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndiaDestionation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.TextField(max_length=35)),
                ('img', models.ImageField(upload_to='pics')),
                ('review', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('desc', models.TextField(max_length=35)),
            ],
        ),
    ]
