# Generated by Django 3.0.10 on 2020-10-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_destination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaDestionation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.TextField(max_length=35)),
                ('img', models.ImageField(upload_to='pics')),
                ('review', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('desc', models.TextField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='IndonasiaDestionation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.TextField(max_length=35)),
                ('img', models.ImageField(upload_to='pics')),
                ('review', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('desc', models.TextField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='JapanDestionation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.TextField(max_length=35)),
                ('img', models.ImageField(upload_to='pics')),
                ('review', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('desc', models.TextField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='NepalDestionation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.TextField(max_length=35)),
                ('img', models.ImageField(upload_to='pics')),
                ('review', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('desc', models.TextField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='ThailandDestionation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.TextField(max_length=35)),
                ('img', models.ImageField(upload_to='pics')),
                ('review', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('desc', models.TextField(max_length=35)),
            ],
        ),
    ]
